version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    build: ./api_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
      - worker2
    environment:
      - REDIS_HOST=redis
      - WORKER_HOST=worker
      - METRICS_HOST=metrics

  worker:
    build: ./worker_service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker2:
    build: ./worker_service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  metrics:
    build: ./metrics_service
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

networks:
  default:
    name: micro_default
